spring.application.name=sb

QUARKUS_REDIS_HOSTS: redis://localhost:6479
QUARKUS_LANGCHAIN4J_OPENAI_API_KEY: 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
QUARKUS_LANGCHAIN4J_OPENAI_ORGANIZATION_ID: org-TcXeHWc7fcNoKSVUoxPhSb9o

